language: java
jdk:
- oraclejdk8
sudo: false
install: ./installViaTravis.sh
script: ./buildViaTravis.sh
env:
  global:
  - secure: Mtyxi0Jq5XSQVjjBFj1Iqh96RjT0kH4TD/Sh/efdxRjrMXD8si74pzeyKZnJEVKRkvZ68QADJhnngi7S7nVzwhYSlCHRgPpihf23yaPTrZQwvbHENB+s5gjaCerRs04QZn5Wi2Pxy6+C/kT85DgCNEzgW1Bi4w8KtAnCBHjepHc=
  - secure: EhJCrVRmKsH5EwjKrne7/Bwy239eTrRJUxnkS9CXwvckrsxmecebE9vgBAU6s5PUxsCMJ/HeOnNJ/MlcS3FoXcCk16w505UtjqOojLy+2KV9ceuuO8oKZ8p1MXkJVNKTn18VmwmsnDKOXNQS4AeqpPZiwBwm4giZnKAgv1fcEYQ=
  - secure: j/rX8B4PMI3b9yADsWi268NetrWXjzIaf+Ms/gr0YaIlIx+0XI7Kpg9c3AOh5vvfL2qecwMXqIxWvG6IUmcFlHLD+/9nvEord+MkMLQ44t4bH/Hl5TXsWAM8Of/DWQFWwq/Z/YIHOvSF5HCFH1m3WbPjjM1R4mQSmge9Ay6hw3Y=
  - secure: TuRke/gu1FGd2oVHv9vRjGSrVYAhvp7LH9l3OTjoQDKHLGucDR2QJF72sOHJ8YFZxIO99RQUXmUsaWkhHhzoQdCOhQbc8CUcNG66p1soappiJxV7WTiqSdRcinoY7VwgGliuwBv+4zObAZcggGi7OZJAxpqnwXia9K/uqseqApE=
cache:
  directories:
  - $HOME/.gradle
